name: Test

on:
    push:
        branches: [ main, dev ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os: [ "ubuntu", "macos", "windows" ]
                cmake: [ "3.20", "3.25" ]
                pytest: [ "6", "7" ]
                python: [ "3.7", "3.8", "3.9", "3.10" ]
                bundled: [ false, true ]

        name: |
            Pytest v${{ matrix.pytest }}
            (${{ matrix.os }}-py${{ matrix.python }} 
            | bundled: ${{ matrix.bundled }})

        runs-on: "${{ matrix.os }}-latest"

        env:
            BUNDLE_PYTHON_TESTS: ${{ matrix.bundled }}

        steps:
            -   uses: actions/setup-python@v4
                with:
                    python-version: "${{ matrix.python }}"

            -   uses: actions/checkout@v3

            -   name: Setup cmake
                uses: jwlawson/actions-setup-cmake@v1.13
                with:
                    cmake-version: "${{ matrix.cmake }}"

            -   name: Install Pytest + Conan
                shell: bash
                run: |
                    pip install \
                        pytest==${{ matrix.pytest }}.* \
                        conan numpy
                    conan profile new default --detect
                    conan profile show default

            -   name: Setup compiler (Linux only)
                if: ${{ matrix.os == 'ubuntu' }}
                run: |
                    conan profile update settings.compiler.libcxx=libstdc++11 default
                    conan profile show default

            -   name: Install Boost Python
                shell: bash
                run: |
                    cd cmake
                    conan install boost/1.80.0@ \
                        --options=boost:without_python=False \
                        --options=boost:without_atomic=True \
                        --options=boost:without_chrono=True \
                        --options=boost:without_container=True \
                        --options=boost:without_context=True \
                        --options=boost:without_contract=True \
                        --options=boost:without_coroutine=True \
                        --options=boost:without_date_time=True \
                        --options=boost:without_exception=True \
                        --options=boost:without_fiber=True \
                        --options=boost:without_filesystem=True \
                        --options=boost:without_graph=True \
                        --options=boost:without_iostreams=True \
                        --options=boost:without_json=True \
                        --options=boost:without_locale=True \
                        --options=boost:without_log=True \
                        --options=boost:without_math=True \
                        --options=boost:without_nowide=True \
                        --options=boost:without_program_options=True \
                        --options=boost:without_random=True \
                        --options=boost:without_regex=True \
                        --options=boost:without_serialization=True \
                        --options=boost:without_stacktrace=True \
                        --options=boost:without_system=True \
                        --options=boost:without_test=True \
                        --options=boost:without_thread=True \
                        --options=boost:without_timer=True \
                        --options=boost:without_type_erasure=True \
                        --options=boost:without_wave=True \
                        --generator=cmake_find_package \
                        --build=missing 

            -   name: Build Example
                shell: bash
                run: |
                    cmake --version \
                    cmake \
                        -DCMAKE_MODULE_PATH:FILEPATH="$(pwd)/cmake" \
                        -S ./example \
                        -B ./build
                    cmake --build ./build --config Release

            -   name: Run Tests
                shell: bash
                working-directory: build
                run: ctest -VV
